/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tn.edu.esprit.covoiturage.GUI;

import java.util.ArrayList;
import java.util.List;
import tn.edu.esprit.covoiturage.DAO.AnnonceDAO;
import tn.edu.esprit.covoiturage.Entities.Annonce;

/**
 *
 * @author amine kh
 */
public class Acceuil extends javax.swing.JFrame {

    /**
     * Creates new form Acceuil
     */
    public Acceuil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnReadMore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new AffichageAnnonce());
        jScrollPane1.setViewportView(jTable1);

        btnReadMore.setText("jButton1");
        btnReadMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadMoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReadMore)
                .addGap(0, 81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnReadMore)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadMoreActionPerformed
        // TODO add your handling code here:
          int tb = jTable1.getSelectedRow();
        if (tb > -1) {
            String t = this.jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0) + "";
            AnnonceDAO ulDao = new AnnonceDAO();
            List<Annonce> lan=new ArrayList<Annonce>();
            lan=ulDao.findAnnonce("Libele",t);
            System.out.println(lan);
Annonce a=new Annonce();
    a.setLibele_annonce(lan.get(0).getLibele_annonce());
    a.setNbr_passager_annonce(lan.get(0).getNbr_passager_annonce());
    a.setPrix_annonce(lan.get(0).getPrix_annonce());
    a.setType_annonce(lan.get(0).getType_annonce());
    a.setType_trajet_annonce(lan.get(0).getType_trajet_annonce());
    a.setFumeur_annonce(lan.get(0).getFumeur_annonce());
    a.setMusic_annonce(lan.get(0).getMusic_annonce());
    a.setBagage_annonce(lan.get(0).getBagage_annonce());
    a.setAnimaux_annonce(lan.get(0).getAnimaux_annonce());
    a.setHeure_depart_annonce(lan.get(0).getHeure_depart_annonce());
    a.setDate_depart_annonce(lan.get(0).getDate_depart_annonce());
    a.setClimatisation_annonce(lan.get(0).getClimatisation_annonce());
    a.setConfort_annonce(lan.get(0).getConfort_annonce());
    a.setLogin_conducteur(lan.get(0).getLogin_conducteur());
    a.setLogin_position_depart(lan.get(0).getLogin_position_depart());
    a.setLogin_position_arrive(lan.get(0).getLogin_position_arrive());
    a.setLogin_position_arret1(lan.get(0).getLogin_position_arret1());
    a.setLogin_position_arret2(lan.get(0).getLogin_position_arret2());
    a.setLogin_position_arret3(lan.get(0).getLogin_position_arret3());
    a.setLogin_position_arret4(lan.get(0).getLogin_position_arret4());
    a.setLogin_position_arret5(lan.get(0).getLogin_position_arret5());
    a.setLogin_position_arret6(lan.get(0).getLogin_position_arret6());
    
    
    GUIReadMore.GetInstance(a).setVisible(true);
            

        }
    }//GEN-LAST:event_btnReadMoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReadMore;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
