/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tn.edu.esprit.covoiturage.GUI;

import tn.edu.esprit.covoiturage.Entities.Utilisateur;
import java.awt.Color;
import java.text.ParseException;
import java.util.List;
import tn.edu.esprit.covoiturage.Controlers.CtrlAjoutUser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import tn.edu.esprit.covoiturage.Controlers.CtrlMenuPrincipal;
import tn.edu.esprit.covoiturage.Controlers.CtrlModifUser;
/**
 *
 * @author AMINE
 */
public class GUIModifUser extends javax.swing.JFrame {

    private static GUIModifUser instance;
    Utilisateur ul;
JTable t;
Utilisateur lu;
    /**
     * Creates new form AjoutPhar
     */



    private GUIModifUser(Utilisateur lu) {
     
        initComponents();
        viderChamps();
        this.lu=lu;
        this.setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         setElem(lu);

    
        
    }

    public static GUIModifUser GetInstance(Utilisateur lu) {
        if (instance == null) {
            
            instance = new GUIModifUser(lu);
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtPassConf = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNaiss = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnRadioHomme = new javax.swing.JRadioButton();
        btnRaddioFemme = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnInscri = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        buttonGroup1.add(btnRadioHomme);
        buttonGroup1.add(btnRaddioFemme);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(14, 2, 5, 5));

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel2.setText("     Login :");
        jPanel1.add(jLabel2);
        jPanel1.add(txtLogin);

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel3.setText("     Mot de passe :");
        jPanel1.add(jLabel3);

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel4.setText("     Confirmer mot de passe :");
        jPanel1.add(jLabel4);

        txtPassConf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassConfKeyTyped(evt);
            }
        });
        jPanel1.add(txtPassConf);

        jLabel12.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel12.setText("     Prenom :");
        jPanel1.add(jLabel12);
        jPanel1.add(txtPrenom);

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel5.setText("     Nom :");
        jLabel5.setAlignmentX(0.5F);
        jPanel1.add(jLabel5);

        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });
        jPanel1.add(txtNom);

        jLabel6.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel6.setText("     Date de naissance : ");
        jPanel1.add(jLabel6);
        jPanel1.add(txtNaiss);

        jLabel7.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel7.setText("     Sexe : ");
        jPanel1.add(jLabel7);

        buttonGroup1.add(btnRadioHomme);
        btnRadioHomme.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRadioHomme.setText("Homme");
        btnRadioHomme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioHommeActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnRaddioFemme);
        btnRaddioFemme.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRaddioFemme.setText("Femme");
        btnRaddioFemme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaddioFemmeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnRadioHomme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRaddioFemme))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRadioHomme)
                    .addComponent(btnRaddioFemme))
                .addGap(5, 5, 5))
        );

        jPanel1.add(jPanel5);

        jLabel8.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel8.setText("     Telephone :");
        jPanel1.add(jLabel8);

        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelKeyTyped(evt);
            }
        });
        jPanel1.add(txtTel);

        jLabel9.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel9.setText("     Email :");
        jPanel1.add(jLabel9);

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        jPanel1.add(txtEmail);
        jPanel1.add(jLabel11);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel1.add(jLabel13);

        btnInscri.setText("S'inscrire");
        btnInscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscriActionPerformed(evt);
            }
        });
        jPanel4.add(btnInscri);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel4.add(btnReset);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setElem(Utilisateur lu){
        
    txtLogin.setText(lu.getLogin_utilisateur());
    txtPass.setText(lu.getMdp_utilisateur());
    txtPrenom.setText(lu.getPrenom_utilisateur());
    txtNom.setText(lu.getNom_utilisateur());
    txtNaiss.setText(lu.getDate_naiss_utilisateur());
    txtTel.setText(lu.getTel_utilisateur());
    txtEmail.setText(lu.getMail_utilisateur());
    
    if(lu.getSexe_utilisateur().equals("Homme")){btnRadioHomme.setSelected(true);
    }else btnRaddioFemme.setSelected(true);
   
}
    
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    //bouton de confirmation de l'ajout
    private void btnInscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscriActionPerformed

        if (!rempliComplet()) {
            JOptionPane.showMessageDialog(rootPane, "Veulliez remplir tout le formulaire !");
        } else if (!CtrlAjoutUser.isValidEmail(txtEmail.getText())) {
            JOptionPane.showMessageDialog(rootPane, "entrez un e-mail valide !");
        }else if (!CtrlAjoutUser.IsPhoneNumber(txtTel.getText())) {
            JOptionPane.showMessageDialog(rootPane, "entrez un Numero d CIN valid !");
        }
        else if (!CtrlAjoutUser.IsSamePass(txtPass.getText().toString(),txtPassConf.getText().toString())) {
            JOptionPane.showMessageDialog(rootPane, "entrez un Mot de passe identique !");
        }
//        else if((!CtrlAjoutUser.IsUsed(txtLogin.getText().toString()))&&!(lu.getLogin_utilisateur().equals(txtLogin.getText().toString()))){
//                       JOptionPane.showMessageDialog(rootPane, "le login est deja utilise !");
// 
//        }
       
        else {
            ul = new Utilisateur();
            ul.setLogin_utilisateur(txtLogin.getText().toString());
            ul.setDate_naiss_utilisateur(txtNaiss.getText().toString());
            ul.setMail_utilisateur(txtEmail.getText().toString());
            ul.setMdp_utilisateur(txtPass.getText().toString());
            ul.setNom_utilisateur(txtNom.getText().toString());
            ul.setPrenom_utilisateur(txtPrenom.getText().toString());
            if(btnRaddioFemme.isSelected())
                ul.setSexe_utilisateur("Femme");
            else
                ul.setSexe_utilisateur("Homme");
            ul.setTel_utilisateur(txtTel.getText().toString());
            ul.setType_utilisateur(1);
            
            
            
            
            
         

                CtrlModifUser.modifieruser(lu.getLogin_utilisateur(), ul);
                CtrlMenuPrincipal.UpdateJtable(t, true);

                JOptionPane.showMessageDialog(rootPane, "Pharmacie ajoutée avec succées");
                viderChamps();
          
           

        }
    }//GEN-LAST:event_btnInscriActionPerformed

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        if (!CtrlAjoutUser.isValidEmail(txtEmail.getText())) {
            txtEmail.setBackground(Color.red);
        } else {
            txtEmail.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyTyped
        String num=txtTel.getText();
        if(!CtrlAjoutUser.IsPhoneNumber(num))   {
            txtTel.setBackground(Color.red);
        }
        else{txtTel.setBackground(Color.white);}// TODO add your handling code here:
    }//GEN-LAST:event_txtTelKeyTyped

    private void txtTelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyReleased
        String num=txtTel.getText();
        if(!CtrlAjoutUser.IsPhoneNumber(num))   {
            txtTel.setBackground(Color.red);
        }
        else{txtTel.setBackground(Color.white);}        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelKeyReleased

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void btnRaddioFemmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaddioFemmeActionPerformed
       
    }//GEN-LAST:event_btnRaddioFemmeActionPerformed

    private void btnRadioHommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioHommeActionPerformed
       
    }//GEN-LAST:event_btnRadioHommeActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void txtPassConfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassConfKeyTyped
    
    }//GEN-LAST:event_txtPassConfKeyTyped

//si l'option jour est selectionnée on met l'horaire d'ouverture/fermeture de 18h à 8h// tester la validité de l'email lors de remplissage du champs du texte
// vider les champs du formulaire aprés l'ajout
    public void viderChamps() {
        txtLogin.setText(null);
        txtEmail.setText(null);
        txtNaiss.setText(null);
        txtNom.setText(null);
        txtPass.setText(null);
        txtPassConf.setText(null);
        txtPrenom.setText(null);
        txtTel.setText(null);
        btnRadioHomme.setSelected(false);
        btnRaddioFemme.setSelected(false);

    }

    //tester le remplissage de tout les champs
    public boolean rempliComplet() {
        if (txtEmail.getText() == null || txtLogin.getText() == null || txtNaiss.getText() == null || txtNom.getText() == null
                || txtPass == null || txtPassConf == null|| txtPrenom == null|| txtTel == null || ((!btnRadioHomme.isSelected() && !btnRaddioFemme.isSelected()))) {
            return false;
        } else {
            return true;
        }
    }

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscri;
    private javax.swing.JRadioButton btnRaddioFemme;
    private javax.swing.JRadioButton btnRadioHomme;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNaiss;
    private javax.swing.JTextField txtNom;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPassConf;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}